import Link from "next/link";
import { CTA, ContactForm, FAQ, SectionTitle, SiteShell, whatsappUrl } from "./GroenicsSite";

const problems = ["Leads are missed or followed up too late.","Attendance, fees, orders, billing or reports are handled manually.","Owners do not get real-time visibility.","Teams depend too much on memory and WhatsApp.","Customer communication is inconsistent.","Revenue leaks happen because there is no proper system."];
const builds: [string, string][] = [
  ["ERP Systems","Custom ERP systems for schools, clinics, manufacturers, distributors and internal business operations."],
  ["AI Automation","Automated follow-ups, reminders, lead capture, reporting, workflow triggers and AI-assisted operations."],
  ["CRM & Sales Systems","Lead tracking, pipelines, reminders, sales dashboards and conversion workflows."],
  ["Dashboards & Reports","Real-time visibility into performance, pending work, revenue, collections and bottlenecks."],
  ["Websites & Portals","Professional websites, admission portals, booking portals, customer portals and landing pages."],
  ["Custom Software","Internal tools, admin panels, staff portals, order systems, billing tools and workflow software."],
];
const offers = [
  ["School ERP & Parent Communication","Schools, coaching centres and educational institutions.","Attendance · Fees · Exams · Admissions · Parent alerts","/school-erp"],
  ["Manufacturing & Distributor Automation","Manufacturers, distributors, wholesalers and production businesses.","Orders · Inventory · Production · Collections","/manufacturing"],
  ["Clinic & Healthcare Automation","Clinics, dental practices and diagnostic centres.","Appointments · Follow-ups · Reminders · CRM","/clinics"],
  ["Custom Business Automation / ERP","Businesses with workflows that ready-made software cannot handle.","Dashboards · ERP modules · AI agents · Integrations","/services"],
];
const demos = [["NaySha EduCore","Built / In Progress","School ERP","Students, teachers, attendance, fees, exams, dashboards and parent communication."],["Restaurant Ordering & Table Booking","Demo","Restaurant System","Menu browsing, table booking, ordering flow and restaurant presentation."],["Manufacturing Order Tracking","Concept / Demo","Manufacturing Automation","Orders, inventory visibility, distributor follow-up and owner dashboards."],["Clinic Appointment Automation","Concept / Demo","Healthcare Automation","Appointments, missed-call capture, reminders and patient follow-up."],["Business Dashboard / CRM","Demo","Business Automation","Leads, tasks, follow-ups, sales and operational performance."]];
const homeFaq: [string,string][] = [
  ["What does Groenics do?","Groenics builds AI automation, ERP systems, CRM systems, dashboards, websites and custom software for businesses that want better control, faster workflows and less manual work."],
  ["Is Groenics only an AI company?","No. Groenics is business-first. AI is used only where it creates practical value. We also build software, dashboards, ERP, CRM, websites and automation systems."],
  ["Which businesses do you work with?","We primarily work with schools, clinics, manufacturers, distributors, SMEs, service businesses and growing companies."],
  ["Do you provide ready-made or custom systems?","Both. Some systems can use existing modules, while others are custom-built around the business workflow."],
  ["How is a project scoped?","We first understand the workflow, users, integrations, implementation needs and desired outcome. Groenics then recommends an appropriate scope and provides a private proposal."],
  ["Can Groenics maintain the system after launch?","Yes. We provide ongoing support, maintenance, improvements and managed automation retainers."],
  ["How do I start?","Book a live demo, message Groenics on WhatsApp or request a free business assessment."],
];

export function GroenicsHome() {
  return <SiteShell><main>
    <section className="gb-hero">
      <div className="gb-hero-copy"><p className="gb-eyebrow">For businesses still running on WhatsApp, Excel, paper and memory</p><h1>Stop losing leads, time and control to <em>manual work.</em></h1><p>Groenics builds practical systems that organise follow-ups, automate repeated work and show owners what is happening across the business—without forcing teams into complicated software.</p><div className="gb-actions"><Link className="gb-button bright" href="#find-your-system">Find the right system</Link><a className="gb-button dark-outline" href={whatsappUrl} target="_blank" rel="noreferrer">Explain your problem on WhatsApp</a></div><Link className="gb-underlink" href="/contact">Get a free workflow assessment →</Link><div className="gb-trust-line"><b>Problem first.</b><span>Built around your workflow.</span><span>Clear implementation and support.</span></div></div>
      <IndustryDecisionPanel />
    </section>
    <IndustryGateway />
    <section className="gb-section gb-problems"><SectionTitle eyebrow="The operating problem" title="Most businesses do not need more software. They need better systems." copy="Growing businesses lose money when work stays scattered across WhatsApp, Excel, paper, calls and disconnected tools."/><div className="gb-problem-grid">{problems.map((p,i)=><article key={p}><span>0{i+1}</span><p>{p}</p></article>)}</div></section>
    <section className="gb-section gb-dark"><SectionTitle light eyebrow="What Groenics builds" title="The operating layer your business is missing." copy="Each system is selected and designed around a defined business problem—not around a software trend."/><div className="gb-build-grid">{builds.map(([title,copy],i)=><article key={title}><span>0{i+1}</span><h3>{title}</h3><p>{copy}</p><Link href="/services">Explore service →</Link></article>)}</div></section>
    <section className="gb-section"><SectionTitle eyebrow="Core offers" title="Focused systems for real business problems."/><div className="gb-offer-list">{offers.map(([title,who,features,href],i)=><article key={title}><span>0{i+1}</span><div><h3>{title}</h3><p>{who}</p></div><strong>{features}</strong><Link href={href}>Discuss system ↗</Link></article>)}</div></section>
    <section className="gb-section gb-proof"><SectionTitle light eyebrow="Honest proof" title="Systems, demos and implementations we are building." copy="No invented clients or fake results. Each item is labelled by its real stage and can be discussed in a walkthrough."/><div className="gb-proof-grid">{demos.map(([title,status,type,copy])=><article key={title}><div><span>{status}</span><small>{type}</small></div><h3>{title}</h3><p>{copy}</p><Link href="/contact">Request walkthrough →</Link></article>)}</div></section>
    <Process />
    <IndustriesStrip />
    <section className="gb-founder"><div><p className="gb-eyebrow">Founder & CEO</p><h2>Built by a founder focused on practical execution.</h2><p>Groenics was founded by Nayab Ahmad with a simple belief: most businesses do not need random software—they need structured systems that reduce manual work, improve follow-ups and give owners better control.</p></div><aside><span>NA</span><h3>Nayab Ahmad</h3><p>Founder & CEO, Groenics · India</p><ul><li>AI automation</li><li>ERP systems</li><li>Business software</li><li>Workflow design</li></ul></aside></section>
    <CTA />
    <section className="gb-section"><SectionTitle eyebrow="Frequently asked" title="Clear answers before we begin."/><FAQ items={homeFaq}/></section>
  </main></SiteShell>;
}

function IndustryDecisionPanel(){const rows=[["Clinic owner","Missed calls · appointments · patient follow-up","/clinics"],["School owner","Fees · attendance · parent communication","/school-erp"],["Manufacturer","Orders · stock · production · collections","/manufacturing"],["Growing business","Leads · workflow · reporting · control","/industries"]];return <aside className="gb-decision-panel"><div className="gb-decision-top"><span>START HERE</span><i>Choose your business</i></div><h2>What do you need to run better?</h2><div className="gb-decision-rows">{rows.map(([title,pain,href],i)=><Link href={href} key={title}><span>0{i+1}</span><div><b>{title}</b><small>{pain}</small></div><i>↗</i></Link>)}</div><p>No obligation. See the exact problems, modules and outcomes for your industry.</p></aside>}
function IndustryGateway(){const items=[{code:"CL",title:"Clinics & healthcare",hook:"Turn missed calls into appointments—and appointments into reliable follow-up.",pain:"Useful if your front desk is overloaded, patients forget visits, or enquiries disappear after the first call.",build:"Appointment booking · missed-call capture · reminders · patient CRM",href:"/clinics",cta:"See clinic automation"},{code:"ED",title:"Schools & education",hook:"Know attendance, fees, admissions and parent communication from one system.",pain:"Useful if records live in registers and sheets, fee follow-up is slow, or parents receive inconsistent updates.",build:"School ERP · fees · attendance · exams · parent alerts",href:"/school-erp",cta:"See school ERP"},{code:"MF",title:"Manufacturing & distribution",hook:"See every order, production stage, stock exception and pending collection.",pain:"Useful if orders arrive on WhatsApp, production status requires phone calls, or payment follow-up is manual.",build:"Orders · production · inventory · distributor CRM · collections",href:"/manufacturing",cta:"See manufacturing system"},{code:"SM",title:"SMEs & service businesses",hook:"Make sure every lead, task, approval and follow-up has an owner and next action.",pain:"Useful if the business depends on your memory, several spreadsheets, or daily chasing for updates.",build:"CRM · workflow automation · owner dashboard · internal tools",href:"/services",cta:"See business systems"}];return <section className="gb-industry-gateway" id="find-your-system"><div className="gb-gateway-heading"><p className="gb-eyebrow">Find your use case</p><h2>See your business problem before you see our technology.</h2><span>Choose the description closest to your operation.</span></div><div className="gb-gateway-grid">{items.map(item=><article key={item.code}><div className="gb-gateway-code">{item.code}</div><h3>{item.title}</h3><strong>{item.hook}</strong><p>{item.pain}</p><small>What we build</small><div className="gb-gateway-build">{item.build}</div><Link href={item.href}>{item.cta} <b>↗</b></Link></article>)}</div></section>}
function Process(){const items=[["Business Diagnosis","Workflow, bottlenecks, revenue leaks and manual processes."],["System Plan","What should be automated, connected, digitised or rebuilt."],["Build & Integrate","Software, ERP, CRM, dashboard, website or internal tool."],["Train & Launch","Practical onboarding so the team can use the system properly."],["Improve & Scale","Measurement, refinement and new automation as the business grows."]];return <section className="gb-section"><SectionTitle eyebrow="Our process" title="How Groenics builds better business systems."/><div className="gb-process">{items.map(([t,c],i)=><article key={t}><span>0{i+1}</span><h3>{t}</h3><p>{c}</p></article>)}</div></section>}
function IndustriesStrip(){const items=[["Schools & Education","Attendance, fees, reports, admissions and parent communication.","/school-erp"],["Clinics & Healthcare","Appointments, follow-ups, reminders and front-desk workload.","/clinics"],["Manufacturers & Distributors","Orders, production, stock, collections and reporting.","/manufacturing"],["SMEs & Local Businesses","Manual work, scattered data, weak follow-up and poor visibility.","/industries"],["Service Businesses","Lead capture, quotations, reminders and operational control.","/industries"]];return <section className="gb-section gb-industries"><SectionTitle eyebrow="Industries" title="Focused systems for businesses that need control."/><div>{items.map(([t,c,h],i)=><Link href={h} key={t}><span>0{i+1}</span><h3>{t}</h3><p>{c}</p><b>↗</b></Link>)}</div></section>}

export type DetailConfig={eyebrow:string;title:string;lead:string;problemTitle:string;problems:string[];solutionTitle:string;solutions:[string,string][];benefits?:string[];cta:string};
export function DetailPage({config}:{config:DetailConfig}){return <SiteShell><main><section className="gb-page-hero"><p className="gb-eyebrow">{config.eyebrow}</p><h1>{config.title}</h1><p>{config.lead}</p><div className="gb-actions"><Link className="gb-button bright" href="/contact#contact-form">{config.cta}</Link><a className="gb-button dark-outline" href={whatsappUrl}>WhatsApp Groenics</a></div><div className="gb-page-index">GROENICS / FOCUSED SYSTEM</div></section><section className="gb-section"><SectionTitle eyebrow="What is going wrong" title={config.problemTitle}/><div className="gb-problem-grid">{config.problems.map((p,i)=><article key={p}><span>0{i+1}</span><p>{p}</p></article>)}</div></section><section className="gb-section gb-dark"><SectionTitle light eyebrow="What we build" title={config.solutionTitle}/><div className="gb-solution-list">{config.solutions.map(([t,c],i)=><article key={t}><span>0{i+1}</span><div><h3>{t}</h3><p>{c}</p></div></article>)}</div></section>{config.benefits&&<section className="gb-section"><SectionTitle eyebrow="Business value" title="What changes when the system works."/><div className="gb-benefit-grid">{config.benefits.map(x=><div key={x}><span>✓</span>{x}</div>)}</div></section>}<Process/><CTA title={config.cta} copy="Tell us how the work happens today. We will show what should be automated, connected or rebuilt."/></main></SiteShell>}

export function ServicesPage(){return <DetailPage config={{eyebrow:"Services built around business outcomes",title:"Practical technology for the work your business depends on.",lead:"From a single automation to a complete ERP, Groenics designs and implements systems around real workflows, users and commercial priorities.",problemTitle:"Technology projects should begin with the business constraint.",problems:["Manual processes consume expensive staff time.","Leads and customers are not followed up consistently.","Important information sits in disconnected tools.","Owners wait for manually prepared reports.","Ready-made software does not fit the workflow.","Websites generate attention but not qualified enquiries."],solutionTitle:"Services that move from diagnosis to implementation.",solutions:builds.concat([["Workflow & WhatsApp Automation","Connected triggers, messages, approvals and reminders around daily operations."],["Business Process Consulting","Workflow diagnosis, system planning and a practical implementation roadmap."]]),benefits:["Reduced manual work","Clearer responsibility","Faster follow-up","Reliable operating visibility","Systems your team can actually use"],cta:"Request a System Audit"}}/>}
export function IndustriesPage(){return <DetailPage config={{eyebrow:"Industries",title:"Focused systems for businesses that need control.",lead:"We translate recurring industry problems into practical modules, workflows and management visibility.",problemTitle:"Different industries. The same costly lack of structure.",problems:["Schools manage records, fees and communication manually.","Clinics lose appointments and follow-up opportunities.","Manufacturers lack order and production visibility.","Distributors track stock and collections across calls and sheets.","SMEs depend heavily on founders and individual memory.","Service businesses lose leads between enquiry and quotation."],solutionTitle:"Systems shaped around the operating context.",solutions:[["Schools","ERP, attendance, fees, exams, admissions, parent alerts and dashboards."],["Clinics","Appointments, missed-call capture, reminders, CRM and billing support."],["Manufacturing","Orders, production, inventory, distributor CRM and owner reporting."],["Distribution","Stock visibility, sales orders, collections and field-team workflows."],["SMEs","CRM, tasks, approvals, dashboards and workflow automation."],["Service Businesses","Lead capture, quotation follow-up, customer tracking and reminders."]],benefits:["One source of reliable information","Less dependence on memory and WhatsApp","Faster customer and lead response","Better management control"],cta:"Discuss Your Industry"}}/>}
export function AboutPage(){return <SiteShell><main><section className="gb-page-hero"><p className="gb-eyebrow">About Groenics</p><h1>Technology used practically. Systems built for real work.</h1><p>Groenics is an AI-powered business solutions company founded by Nayab Ahmad to help growing businesses move from scattered manual operations to structured, measurable systems.</p></section><section className="gb-section gb-about-grid"><div><p className="gb-eyebrow">Mission</p><h2>Use technology for measurable business improvement—not for show.</h2></div><p>Our mission is to reduce manual work, improve visibility, recover lost opportunities and help businesses scale operations with more control.</p><div><p className="gb-eyebrow">Vision</p><h2>Build a serious business systems company from India.</h2></div><p>We aim to serve local businesses, growing companies and global clients with practical AI, automation, ERP and software solutions.</p></section><section className="gb-founder"><div><p className="gb-eyebrow">Founder story</p><h2>A belief in practical execution.</h2><p>Nayab Ahmad founded Groenics around a simple observation: businesses often buy tools while the real workflow remains broken. Groenics starts by understanding the work, then builds only what creates meaningful control, speed or visibility.</p></div><aside><span>NA</span><h3>Nayab Ahmad</h3><p>Founder & CEO · India</p><ul><li>Business-first philosophy</li><li>Direct founder involvement</li><li>Honest proof</li><li>Practical delivery</li></ul></aside></section><CTA/></main></SiteShell>}
export function ContactPage(){return <SiteShell><main><section className="gb-contact-page"><div><p className="gb-eyebrow">Contact Groenics</p><h1>Let’s find what your business should automate next.</h1><p>Tell us what is currently manual, slow, scattered or difficult to track. We will suggest what can be improved.</p><a href={whatsappUrl} target="_blank" rel="noreferrer">WhatsApp +91 93342 06953 ↗</a><div className="gb-contact-points"><span>Free initial assessment</span><span>Response within one business day</span><span>India · Remote delivery available</span></div></div><ContactForm detailed/></section></main></SiteShell>}
