"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { supabase } from "@/lib/supabase";
import { ProjectProfitability } from "@/lib/types";
import { EmptyState, LoadingState } from "@/components/Portal/States";
import { FormInput } from "@/components/Portal/FormInputs";

type LeadRow={id:string;client_name:string;pipeline_stage:string;lead_temperature:string;expected_project_value:number|null;probability_of_closing:number|null;lost_reason:string|null;source:string|null;next_action_at:string|null;created_at:string;updated_at:string};
type InvoiceRow={id:string;invoice_number:string;amount:number;status:string;due_date:string;created_at:string};
type PaymentRow={invoice_id:string;amount:number;payment_date:string};
type ProjectRow={id:string;project_name:string;status:string;due_date:string|null;updated_at:string};
type MilestoneRow={project_id:string;title:string;status:string;due_date:string|null};
type ProposalRow={id:string;status:string;issue_date:string};
type ActivityRow={action:string;created_at:string};
type EventRow={event_type:string;status:string;start_at:string};
type VisitRow={status:string;appointment_at:string};
type FollowupRow={status:string;follow_up_date:string};
type ExpenseRow={amount:number};
type TodayRow={record_type:string;status:string;action_date:string;completed_at:string|null};

const money=(value:number)=>`Rs. ${Number(value||0).toLocaleString("en-IN",{maximumFractionDigits:0})}`;
const dateString=(date:Date)=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`;
function monday(date:Date){const result=new Date(date);const day=(result.getDay()+6)%7;result.setDate(result.getDate()-day);return dateString(result);}
function addDays(value:string,days:number){const date=new Date(`${value}T00:00:00`);date.setDate(date.getDate()+days);return dateString(date);}
function Card({label,value}:{label:string;value:string}){return <article className="rounded-xl border border-white/10 bg-black/20 p-4"><p className="text-xs text-gray-500">{label}</p><p className="mt-2 text-xl font-bold text-white">{value}</p></article>;}

export default function WeeklyReportPage(){
  const [weekStart,setWeekStart]=useState("");const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [data,setData]=useState<Record<string,unknown>|null>(null);
  useEffect(()=>{const timer=window.setTimeout(()=>setWeekStart(monday(new Date())),0);return()=>window.clearTimeout(timer);},[]);
  const weekEnd=weekStart?addDays(weekStart,6):"";
  const load=useCallback(async()=>{if(!weekStart)return;setLoading(true);setError("");try{const {data:ventures}=await supabase.from("ventures").select("id").eq("status","Active").is("archived_at",null).order("is_default",{ascending:false}).order("created_at",{ascending:true}).limit(1);if(!ventures?.length)throw new Error("No active venture.");const id=ventures[0].id;
    const [leadR,activityR,eventR,proposalR,invoiceR,expenseR,projectR,milestoneR,visitR,followupR,todayR,profitR]=await Promise.all([
      supabase.from("leads").select("id,client_name,pipeline_stage,lead_temperature,expected_project_value,probability_of_closing,lost_reason,source,next_action_at,created_at,updated_at").eq("venture_id",id).is("archived_at",null),
      supabase.from("activity_logs").select("action,created_at").eq("venture_id",id).gte("created_at",`${weekStart}T00:00:00+05:30`).lte("created_at",`${weekEnd}T23:59:59+05:30`),
      supabase.from("calendar_events").select("event_type,status,start_at").eq("venture_id",id).gte("start_at",`${weekStart}T00:00:00+05:30`).lte("start_at",`${weekEnd}T23:59:59+05:30`),
      supabase.from("proposals").select("id,status,issue_date").eq("venture_id",id).is("archived_at",null).gte("issue_date",weekStart).lte("issue_date",weekEnd),
      supabase.from("invoices").select("id,invoice_number,amount,status,due_date,created_at").eq("venture_id",id).is("archived_at",null),
      supabase.from("expenses").select("amount").eq("venture_id",id).is("archived_at",null).gte("expense_date",weekStart).lte("expense_date",weekEnd),
      supabase.from("projects").select("id,project_name,status,due_date,updated_at").eq("venture_id",id).is("archived_at",null),
      supabase.from("project_milestones").select("project_id,title,status,due_date"),
      supabase.from("field_visits").select("status,appointment_at").eq("venture_id",id).is("archived_at",null).gte("appointment_at",`${weekStart}T00:00:00+05:30`).lte("appointment_at",`${weekEnd}T23:59:59+05:30`),
      supabase.from("followups").select("status,follow_up_date").eq("venture_id",id).is("archived_at",null).gte("follow_up_date",weekStart).lte("follow_up_date",weekEnd),
      supabase.from("today_action_items").select("record_type,status,action_date,completed_at").eq("venture_id",id).gte("action_date",weekStart).lte("action_date",weekEnd),
      supabase.from("project_profitability").select("*").eq("venture_id",id)
    ]);if(leadR.error||proposalR.error||invoiceR.error||expenseR.error||projectR.error)throw (leadR.error||proposalR.error||invoiceR.error||expenseR.error||projectR.error);
    const leads=(leadR.data||[]) as LeadRow[],activities=(activityR.data||[]) as ActivityRow[],events=(eventR.data||[]) as EventRow[],proposals=(proposalR.data||[]) as ProposalRow[],invoices=(invoiceR.data||[]) as InvoiceRow[],expenses=(expenseR.data||[]) as ExpenseRow[],projects=(projectR.data||[]) as ProjectRow[],milestones=(milestoneR.data||[]) as MilestoneRow[],visits=visitR.error?[]:(visitR.data||[]) as VisitRow[],followups=(followupR.data||[]) as FollowupRow[],todayItems=(todayR.data||[]) as TodayRow[],profits=profitR.error?[]:(profitR.data||[]) as ProjectProfitability[];
    const invoiceIds=invoices.map(x=>x.id);const paymentR=invoiceIds.length?await supabase.from("payments").select("invoice_id,amount,payment_date").in("invoice_id",invoiceIds):{data:[],error:null};const payments=((paymentR.data||[]) as PaymentRow[]);const periodPayments=payments.filter(x=>x.payment_date>=weekStart&&x.payment_date<=weekEnd);const paid=new Map<string,number>();payments.forEach(x=>paid.set(x.invoice_id,(paid.get(x.invoice_id)||0)+Number(x.amount)));
    const openLeads=leads.filter(x=>!["Won","Lost"].includes(x.pipeline_stage));const won=leads.filter(x=>x.pipeline_stage==="Won"&&x.updated_at.slice(0,10)>=weekStart&&x.updated_at.slice(0,10)<=weekEnd);const lost=leads.filter(x=>x.pipeline_stage==="Lost"&&x.updated_at.slice(0,10)>=weekStart&&x.updated_at.slice(0,10)<=weekEnd);const overdueInv=invoices.filter(x=>!["Paid","Cancelled","Draft"].includes(x.status)&&x.due_date<weekEnd&&Number(x.amount)>(paid.get(x.id)||0));const risks=projects.filter(x=>x.status==="On Hold"||(x.due_date&&x.due_date<weekEnd&&!["Completed","Cancelled"].includes(x.status)));const blocked=milestones.filter(x=>x.status==="Blocked"||(x.due_date&&x.due_date<weekEnd&&x.status!=="Done"));
    const attention=[...openLeads].sort((a,b)=>(b.lead_temperature==="Hot"?1:0)-(a.lead_temperature==="Hot"?1:0)||Number(b.expected_project_value||0)-Number(a.expected_project_value||0)).filter(x=>x.lead_temperature==="Hot"||!x.next_action_at||x.next_action_at.slice(0,10)<=weekEnd).slice(0,5);
    const stageCounts=new Map<string,number>();openLeads.forEach(x=>stageCounts.set(x.pipeline_stage,(stageCounts.get(x.pipeline_stage)||0)+1));const bottleneck=[...stageCounts.entries()].sort((a,b)=>b[1]-a[1])[0];const priorities=[attention[0]&&`Advance ${attention[0].client_name}`,overdueInv[0]&&`Collect ${overdueInv[0].invoice_number}`,risks[0]&&`Unblock ${risks[0].project_name}`].filter(Boolean);
    setData({leads,activities,events,proposals,invoices,expenses,projects,milestones,visits,followups,todayItems,profits,payments:periodPayments,openLeads,won,lost,overdueInv,risks,blocked,attention,bottleneck:bottleneck?`${bottleneck[0]} has ${bottleneck[1]} open leads`:"Insufficient pipeline data",priorities});
  }catch(c){setError(c instanceof Error?c.message:"Unable to calculate weekly report.");}finally{setLoading(false);}},[weekEnd,weekStart]);
  useEffect(()=>{const timer=window.setTimeout(load,0);return()=>window.clearTimeout(timer);},[load]);
  const d=data as null|{leads:LeadRow[];activities:ActivityRow[];events:EventRow[];proposals:ProposalRow[];invoices:InvoiceRow[];expenses:ExpenseRow[];projects:ProjectRow[];milestones:MilestoneRow[];visits:VisitRow[];followups:FollowupRow[];todayItems:TodayRow[];profits:ProjectProfitability[];payments:PaymentRow[];openLeads:LeadRow[];won:LeadRow[];lost:LeadRow[];overdueInv:InvoiceRow[];risks:ProjectRow[];blocked:MilestoneRow[];attention:LeadRow[];bottleneck:string;priorities:string[]};
  const metrics=useMemo(()=>{if(!d)return null;const pipeline=d.openLeads.reduce((s,x)=>s+Number(x.expected_project_value||0),0);const weighted=d.openLeads.reduce((s,x)=>s+Number(x.expected_project_value||0)*Number(x.probability_of_closing||0)/100,0);const invoiced=d.invoices.filter(x=>x.created_at.slice(0,10)>=weekStart&&x.created_at.slice(0,10)<=weekEnd&&x.status!=="Cancelled").reduce((s,x)=>s+Number(x.amount),0);const collections=d.payments.reduce((s,x)=>s+Number(x.amount),0);const expenses=d.expenses.reduce((s,x)=>s+Number(x.amount),0);return{pipeline,weighted,invoiced,collections,expenses,outstanding:d.overdueInv.reduce((s,x)=>s+Number(x.amount),0),gross:d.profits.reduce((s,x)=>s+Number(x.gross_profit),0),conversations:d.activities.filter(x=>["customer_interaction_completed","followup_logged","next_action_completed"].includes(x.action)).length,meetings:d.events.filter(x=>x.status==="Completed"&&x.event_type.toLowerCase().includes("meeting")).length,demos:d.events.filter(x=>x.status==="Completed"&&x.event_type==="Demonstration").length};},[d,weekEnd,weekStart]);
  if(loading||!weekStart)return <LoadingState/>;if(error)return <p className="rounded-xl bg-red-500/10 p-4 text-red-200">{error}</p>;if(!d||!metrics)return <EmptyState icon="W" title="No weekly data" description="Add records to calculate the CEO report."/>;
  const sales=[["New leads",String(d.leads.filter(x=>x.created_at.slice(0,10)>=weekStart&&x.created_at.slice(0,10)<=weekEnd).length)],["Conversations",String(metrics.conversations)],["Meetings",String(metrics.meetings)],["Demonstrations",String(metrics.demos)],["Proposals",String(d.proposals.length)],["Deals won",String(d.won.length)],["Deals lost",String(d.lost.length)],["Pipeline",money(metrics.pipeline)],["Weighted pipeline",money(metrics.weighted)]];
  const finance=[["Invoiced",money(metrics.invoiced)],["Collections",money(metrics.collections)],["Expenses",money(metrics.expenses)],["Overdue amount",money(metrics.outstanding)],["Project gross profit",money(metrics.gross)]];
  const delivery=[["Active projects",String(d.projects.filter(x=>x.status==="Active").length)],["Completed",String(d.projects.filter(x=>x.status==="Completed"&&x.updated_at.slice(0,10)>=weekStart&&x.updated_at.slice(0,10)<=weekEnd).length)],["At-risk projects",String(d.risks.length)],["Blocked milestones",String(d.blocked.length)],["Average margin",d.profits.length?`${(d.profits.reduce((s,x)=>s+Number(x.gross_margin||0),0)/d.profits.length).toFixed(1)}%`:"—"]];
  const execution=[["Field visits",String(d.visits.filter(x=>x.status==="Completed").length)],["Follow-ups completed",String(d.followups.filter(x=>x.status==="Done").length)],["Overdue actions",String(d.todayItems.filter(x=>!["Completed","Cancelled"].includes(x.status)&&x.action_date<weekEnd).length)],["Content published",String(d.todayItems.filter(x=>x.record_type==="Content"&&x.status==="Completed").length)],["Content-attributed leads",String(d.leads.filter(x=>x.source?.toLowerCase().includes("content")&&x.created_at.slice(0,10)>=weekStart&&x.created_at.slice(0,10)<=weekEnd).length)],["Traceable content revenue",money(d.won.filter(x=>x.source?.toLowerCase().includes("content")).reduce((s,x)=>s+Number(x.expected_project_value||0),0))]];
  return <div className="space-y-6 print:bg-white print:text-black"><header className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><Link href="/portal/reports" className="text-xs text-amber-300 print:hidden">← Reports</Link><h1 className="mt-2 text-3xl font-bold text-white print:text-black">Weekly CEO Report</h1><p className="text-sm text-gray-400">{weekStart} to {weekEnd}</p></div><div className="flex flex-wrap gap-2 print:hidden"><button onClick={()=>setWeekStart(monday(new Date()))} className="rounded-lg bg-white/10 px-3 py-2 text-sm">Current week</button><button onClick={()=>setWeekStart(addDays(monday(new Date()),-7))} className="rounded-lg bg-white/10 px-3 py-2 text-sm">Previous week</button><FormInput type="date" value={weekStart} onChange={e=>setWeekStart(monday(new Date(`${e.target.value}T00:00:00`)))}/><button onClick={()=>window.print()} className="rounded-lg bg-amber-300 px-3 py-2 text-sm font-bold text-black">Print / Save PDF</button></div></header>
  {[["Sales",sales],["Finance",finance],["Delivery",delivery],["Founder execution",execution]].map(([title,items])=><section key={title as string}><h2 className="mb-3 text-lg font-bold text-amber-200 print:text-black">{title as string}</h2><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{(items as string[][]).map(([label,value])=><Card key={label} label={label} value={value}/>)}</div></section>)}
  <section className="grid gap-4 lg:grid-cols-2"><div className="rounded-xl border border-red-500/20 bg-red-500/5 p-4"><h2 className="font-bold text-red-200">Biggest bottleneck</h2><p className="mt-2 text-sm text-gray-300">{d.bottleneck}</p></div><div className="rounded-xl border border-amber-300/15 p-4"><h2 className="font-bold text-white">Next week’s top priorities</h2><ol className="mt-2 list-decimal pl-5 text-sm text-gray-300">{d.priorities.map(x=><li key={x}>{x}</li>)}</ol></div><List title="Five leads needing attention" rows={d.attention.map(x=>`${x.client_name} · ${x.lead_temperature} · ${money(Number(x.expected_project_value||0))}`)}/><List title="Three overdue financial actions" rows={d.overdueInv.slice(0,3).map(x=>`${x.invoice_number} · due ${x.due_date} · ${money(x.amount)}`)}/><List title="Three delivery risks" rows={[...d.risks.map(x=>`${x.project_name} · ${x.status}`),...d.blocked.map(x=>`${x.title} · ${x.status}`)].slice(0,3)}/><List title="Loss reasons" rows={d.lost.map(x=>x.lost_reason||"No loss reason recorded")}/></section>
  <p className="text-xs text-gray-600">Content revenue is shown only when a won lead’s source explicitly contains “content.” Financial figures are operational, not statutory accounts.</p></div>;
}
function List({title,rows}:{title:string;rows:string[]}){return <div className="rounded-xl border border-white/10 p-4"><h2 className="font-bold text-white print:text-black">{title}</h2>{rows.length?<ul className="mt-2 space-y-2 text-sm text-gray-300 print:text-black">{rows.map((x,i)=><li key={`${x}-${i}`}>{x}</li>)}</ul>:<p className="mt-2 text-sm text-gray-500">None identified.</p>}</div>;}
